version: '3.9'

services:
    my-app:
      image: codehub/dotnet:latest
      container_name: dotnet_app
      build:
          context: .

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: 127.0.0.1
